### ISSUE TITLE
update-motd is installed but cannot operate on read-only /

### ISSUE THREAD

**Issue by zyga** [snapcore/core18#117]
The login experience to uc18 device is not great:

```
localhost login: zyga
Password: 
Last login: Wed Jan 30 14:08:45 UTC 2019 on ttyMSM0
/etc/update-motd.d/50-motd-news: 59: /etc/update-motd.d/50-motd-news: cannot create /var/cache/motd-news: Read-only file system
run-parts: /etc/update-motd.d/50-motd-news exited with return code 2
 * Ubuntu Core:     https://www.ubuntu.com/core
 * Community:       https://forum.snapcraft.io
 * Snaps:           https://snapcraft.io

This Ubuntu Core 18 machine is a tiny, transactional edition of Ubuntu,
designed for appliances, firmware and fixed-function VMs.

If all the software you care about is available as snaps, you are in
the right place. If not, you will be more comfortable with classic
deb-based Ubuntu Server or Desktop, where you can mix snaps with
traditional debs. It's a brave new world here in Ubuntu Core!

Please see 'snap --help' for app installation and updates.
zyga@localhost:~$ 
```

As we can see the update-message-of-the-day mechanism is active but incompatible with read only filesystem used by ubuntu core.

```
/etc/update-motd.d/50-motd-news: 59: /etc/update-motd.d/50-motd-news: cannot create /var/cache/motd-news: Read-only file system
```

**Comment by zyga** [comment]
This issue only affects core18, a core16 system doesn't have update-motd

**Comment by vorlonofportland** [comment]
On Wed, Jan 30, 2019 at 07:04:36AM -0800, Zygmunt Krynicki wrote:
> The login experience to uc18 device is not great:

> ```
> localhost login: zyga
> Password: 
> Last login: Wed Jan 30 14:08:45 UTC 2019 on ttyMSM0
> /etc/update-motd.d/50-motd-news: 59: /etc/update-motd.d/50-motd-news: cannot create /var/cache/motd-news: Read-only file system
> run-parts: /etc/update-motd.d/50-motd-news exited with return code 2
>  * Ubuntu Core:     https://www.ubuntu.com/core
>  * Community:       https://forum.snapcraft.io
>  * Snaps:           https://snapcraft.io
> 
> This Ubuntu Core 18 machine is a tiny, transactional edition of Ubuntu,
> designed for appliances, firmware and fixed-function VMs.
> 
> If all the software you care about is available as snaps, you are in
> the right place. If not, you will be more comfortable with classic
> deb-based Ubuntu Server or Desktop, where you can mix snaps with
> traditional debs. It's a brave new world here in Ubuntu Core!
> 
> Please see 'snap --help' for app installation and updates.
> zyga@localhost:~$ 
> ```

> As we can see the update-message-of-the-day mechanism is active but
> incompatible with read only filesystem used by ubuntu core.

> ```
> /etc/update-motd.d/50-motd-news: 59: /etc/update-motd.d/50-motd-news: cannot create /var/cache/motd-news: Read-only file system
> ```

I see two possible bugs here, I'm not sure if we should be fixing one or the
other or both.

 - Should /var/cache be part of the read-only space on UC18 or should it be
   writable?  According to the FHS this directory is meant to be writable. 
   Is there an argument why it should NOT be writable in UC18?  (Even though
   nothing except the core snap itself will be able to write to it)
 - Should update-motd be included in UC18 at all?  Should this be part of
   the Core experience or not?

I don't know if there was specific discussion about update-motd inclusion in
UC18 or if this was inherited by default.

-- 
Steve Langasek                   Give me a lever long enough and a Free OS
Debian Developer                   to set it on, and I can move the world.
Ubuntu Developer                                   https://www.debian.org/
slangasek@ubuntu.com                                     vorlon@debian.org

**Comment by woodrow-shen** [comment]
This bug also affects me too. Can someone have any update or suggestion?

**Comment by vorlonofportland** [comment]
@mvo5 @pedronis do either of you have an objection to /var/cache being mounted writable on UC18?  This seems per se correct to me.

**Comment by woodrow-shen** [comment]
The bug can be fixed by creating /var/cache/motd-news file but I'm curious of how update-motd was not landed under /etc/update-motd.d/* existed.

**Comment by WillNilges** [comment]
Sorry for necrobumping, but I would like to edit `/etc/issue` and `/etc/motd`, but, well, Core uses a read-only filesystem for `/`. Also, despite the fact that I am, in fact, using Core18, I don't have `update-motd`. What can I do?

**Comment by Meulengracht** [comment]
If there is any need for changing the motd this will have to be done before building core18. /var/cache has been made writable as mentioned in the PR linked to this issue, and we will close this issue as resolved.
