### ISSUE TITLE
fw_printenv is not present in core18

### ISSUE THREAD

**Issue by zyga** [snapcore/core18#118]
A dragon board with Ubuntu Core 18 (that is core18 as bootable base, snapd as a snap) doesn't provide the `fw_printenv` binary. The binary is present in the core snap but not in the core18 snap.

```
zyga@localhost:~$ find / -name fw_printenv 2>/dev/null 
/snap/core/x1/usr/bin/fw_printenv
/snap/core/6261/usr/bin/fw_printenv
/writable/system-data/snap/core/x1/usr/bin/fw_printenv
/writable/system-data/snap/core/6261/usr/bin/fw_printenv
```

```
zyga@localhost:~$ snap list
Name                Version       Rev   Tracking  Publisher   Notes
core                16-2.37       6261  stable    canonical✓  core
core18              18            638   beta      canonical✓  base
dragonboard         18-1          44    18/beta   canonical✓  gadget
dragonboard-kernel  4.15.0-44.47  78    18/beta   canonical✓  kernel
snapd               2.37.1        2250  beta      canonical✓  snapd
test-snapd-rsync    3.1.3         9     stable    cachio      devmode
```

The binary is clearly used in snapd test suite. The particular test I ran was `ubuntu-core-16-arm-64:tests/main/failover:rclocalcrash` but it is not specific to that test.

Tail log from failed test:
```
-----
+ rm -f failing.snap failBoot currentBoot prevBoot
+ rm -rf /home/tmp
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/boot.sh
++ GRUB_EDITENV=grub-editenv
++ case "$SPREAD_SYSTEM" in
+ bootenv_unset snap_try_core
+ local var=snap_try_core
+ command -v grub-editenv
+ fw_setenv snap_try_core
/home/gopath/src/github.com/snapcore/snapd/tests/lib/boot.sh: line 33: fw_setenv: command not found
```

**Comment by mvo5** [comment]
Fwiw, this is only an issue in the tests - the regular system does not need fw_{get,set}env

**Comment by vorlonofportland** [comment]
On Wed, Jan 30, 2019 at 08:31:52AM -0800, Michael Vogt wrote:
> Fwiw, this is only an issue in the tests - the regular system does not
> need fw_{get,set}env

Should we be including test-only dependencies in the core18 snap?  Or should
the tests be modified to not require it?

**Comment by mvo5** [comment]
I think the test should be changed, unless there is a strong(er) reason we don't really need this in core18.

**Comment by mvo5** [comment]
Feel free to reopen if you disagree and we can discuss further.
