### ISSUE TITLE
Having issues installing core18

### ISSUE THREAD

**Issue by Aadniz** [snapcore/core18#128]
OS: Debian GNU/Linux 9.9 (stretch) x86_64
Kernal: 4.9.0-9-amd64

---

Hi.

I'm trying to install League of Legends via snap but get this error message:

```
$ sudo snap install leagueoflegends --edge
error: cannot perform the following tasks:
- Mount snap "leagueoflegends" (35) (cannot find required base "core18")
```

I cloned the core18 git, but can't quite figure out how to install it.

I tried installing core18 via snap with this command:
`$ sudo snap install core18`

But I get this error message:
`error: cannot install "core18": invalid snap type: "base"`

I then tried to install snapcraft, but was unable to add the repository:
`W: The repository 'http://ppa.launchpad.net/snappy-dev/tools/ubuntu eoan InRelease' is not signed.`

---

Are there any easy way to install core18 ?

**Comment by Aadniz** [comment]
This command fixed the issue:
`sudo snap install core`

**Comment by akkida746** [comment]
Yes it worked. Thanks !

**Comment by gonzoibox** [comment]
Indeed, it works! THNX
