### ISSUE TITLE
iptables not present in core18

### ISSUE THREAD

**Issue by albertodonato** [snapcore/core18#132]
The iptables binary is not included in core18, so even a snap with the `firewall-control` plug connected can't access it

**Comment by vorlonofportland** [comment]
This sounds like it makes sense, but I wonder why this wasn't identified earlier as a requirement.  @pedronis is there a list somewhere of interfaces that snapd expects to be provided by the core18 snap?

**Comment by mvo5** [comment]
Yes, we should add iptables back. About the second part of the question - we are working on code that can check requirements for interfaces. Its a bit tricky as it requires simulating interface connections and parsing the apparmor rules this is why its not run on core18 yet. But it will be soon. Sorry for the trouble.
