### ISSUE TITLE
Stuck with blank screen on snap-core 18 Raspi 3 B+ install

### ISSUE THREAD

**Issue by bernermic** [snapcore/core18#142]
I can not login to the system anymore.  This happened probably after a update without any interaction on the machine.

After power off and on again I can see the Ubuntu-Core logo for some time and afterwards a blinking cursor without any further information.
This machine did run and update for about an year without any issue.

Looking at the files on the SD card I can see this changed snap versions which are in the questionable time:  
   pi-kernel 58  
   core18 snap 1226

My Raspberry pi is a model 3 b+ with an Ubuntu-core 18.

I am a bit lost where to begin to analyse this now. Can someone please guide me to analyze/resolve this issue?

**Comment by bernermic** [comment]
Maybe it is only me having this weird issue. I'll just leave the SD card as it is for now. Maybe someone has an idea.
I would like to analyse this to get a proper bug report.

If it only a one of weird issue I have I will close this. Can anyone give me an opinion about this?

**Comment by Meulengracht** [comment]
Closing due to inacitivty for 2 years - if you still experience this issue please try to hook up an usb-to-ttl and get some serial output of the boot, and then feel free to reopen the issue and we will look into this.
