### ISSUE TITLE
missing /etc/cloud/cloud.cfg.d/99-snappy-azure.cfg

### ISSUE THREAD

**Issue by anonymouse64** [snapcore/core18#153]
The core snap has this file but I don't know why it has it or if it's necessary, the git log for the core snap  seems to imply that it came from the ubuntu-core-config debian pkg, but the earliest reference to this file I could find is: https://github.com/snapcore/core-build/commit/aac9e1cace318401eff1a5dbf14a81f5566e6f8e which implies that this file even predates that...

Is this file necessary anymore in the core18 / core20 snaps? It seems no since nobody has complained about it, but still just curious about this discrepancy.

**Comment by Meulengracht** [comment]
@anonymouse64 We are not able to observe this file anymore in core20 and core18, I will close this issue. If you are still able to see this file Ian, you can reopen the issue.
