### ISSUE TITLE
quoting fix for timedatectl wrapper got lost between core16 and core18

### ISSUE THREAD

**Issue by ogra1** [snapcore/core18#158]
https://github.com/snapcore/core/pull/64/commits/054f0dc8078d356b3abd83b460d0753202d3878c

is missing in core18

**Comment by mvo5** [comment]
This PR https://github.com/snapcore/core18/pull/159 should fix it.

**Comment by Meulengracht** [comment]
Closing this issue as resolved, feel free to reopen should the issue persist.
