### ISSUE TITLE
Beef up build instructions

### ISSUE THREAD

**Issue by WillNilges** [snapcore/core18#162]
The build instructions, to put it bluntly, aren't super helpful. Might I suggest we get together some more complete documentation on how one should go about building this snap on various platforms? Sure, x86 is easy, but getting this to snap to craft on a Raspberry Pi took hours of internet archaeology.

See issue #161 .

**Comment by Meulengracht** [comment]
There has been some added instructions on the preferred way of building on other archs. You can indeed use privileged LXD containers as well, but it's easier to use remote-build in snapcraft. I'm closing this, but feel free to reopen if you feel the instructions insufficient.
