### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kabo** [snapcore/core18#173]
I can't seem to find the license for core18?

**Comment by xnox** [comment]
core18 is a collection of software built from Ubuntu Main. It contains a collection of software licensed under different terms.

Please see https://ubuntu.com/licensing what it means for software to be in Ubuntu Main.

You can also get tarballs from http://cdimage.ubuntu.com/ubuntu-base/releases/18.04.5/release/ which include full dpkg/apt database files and have slightly more documentation about licenses in /usr/share/doc/*/copyright files.
