### ISSUE TITLE
systemd can't unmount disk

### ISSUE THREAD

**Issue by montvid** [snapcore/core18#176]
I am running this default systemd mount script https://paste.gnome.org/pfdd01u96 and when I stop or disable the script the disk is unmounted but commands like fsck or resize2fs can't use it as it is still in use by something. Regular mount and umount commands work fine and the dis is not in use. The systemd script is fine so there is somekind of a problem with ubuntu core 18? How can I check what is using the disk anyway? The mount command says it is unmounted.

**Comment by montvid** [comment]
This script from writable.mount is also unable to unmount my disk so fsck could run.
```
[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target
[Mount]
Where=/media
What=/dev/disk/by-uuid/c77ceebc-73e2-4807-a82f-2cf92811b88a
```

**Comment by anonymouse64** [comment]
I imagine that what is happening is that after /media is mounted by this script, /media is then bind mounted into the mount namespace of any snaps that are running on the Ubuntu Core system. What is the output of 

```
cat /proc/self/mountinfo
```

and 

```
for m in $(ls /run/snapd/ns/*.mnt); do echo -n "$m: "; sudo nsenter --mount=$m sh -c 'cat /proc/self/mountinfo | grep media'; done
```

**Comment by Meulengracht** [comment]
Closing this issue due to age of issue. Feel free to reopen the issue with requested information should this still be relevant.
