### ISSUE TITLE
Removal of expired Let's Encrypt certificate

### ISSUE THREAD

**Issue by SandJ** [snapcore/core18#182]
I hope this is the right place to raise this.
There is a Let's Encrypt certificate which expired on 30th September 2021.  It is included in this snap.
Many web sites that have this certificate validating them are not working.  One easy fix is to remove the "DST_Root_CA_X3.crt" certificate from the server and comment out its reference in /etc/ca-certificates.conf
However, when it is included in the core18 snap (and core20 actually) this is not so straightforward - one cannot delete files from the snap.
I *think* this snap should have that certificate removed.

(I tried to use unsquashfs to expand core18, remove reference to the certificate and rebuild the snap, but it ended up flagged as 'broken' so I am out of my depth trying to do that for myself.)

**Comment by anonymouse64** [comment]
The certificate file in question comes from the ca-certificates package which will probably be updated in the snap when the core18 snap gets rebuilt and pushed out, which happens once every few weeks as I understand it. So I think this should just automatically happen without any effort, just the maintainers rebuilding the snap which happens automatically, should resolve it. 

Out of curiosity did you check the edge channel of the core18 snap for this certificate being present?

**Comment by sil2100** [comment]
We have new core20 and core18 snaps in the pipeline, right now in certification testing phase.

**Comment by SandJ** [comment]
> Out of curiosity did you check the edge channel of the core18 snap for this certificate being present?

Thank you for the question; I knew almost nothing about snap files and that was enough to trigger the right Google searches to slightly illuminate me.

The edge and beta channels do not have the certificate; candidate and stable do.  I have refreshed the snap on the server in question with the beta channel version.

Thank you for your help.  I am a little wiser about what snap info's output means now.

**Comment by Meulengracht** [comment]
We have confirmed it fixed in latest snap build, so we will close the issue, if it should be an issue for you still please reopen the issue.
