### ISSUE TITLE
Sensible version number

### ISSUE THREAD

**Issue by mvo5** [snapcore/core18#56]
The current version number of the core18 snap is "0.1" which is ok for the edge channel but not once we move  towards beta/candidate/stable.

This is a bit of an RFC how how to pick the right version: 18.04-$seq ? where the sequence always increases? E.g. 18.04-232 and once we release a po int release we move to 18.04.1-$seq? Or should it be date based? 18.04-20180919 to indicate when the last build happend?

The opinion of @niemeyer here would be especially valuable.

**Comment by sil2100** [comment]
I guess I'd prefer 18.04-$seq or 18-$seq myself.

**Comment by Meulengracht** [comment]
The output from snap info core18
latest/stable:    20211015 2021-10-27 (2246) 58MB -
latest/candidate: 20211015 2021-10-18 (2246) 58MB -
latest/beta:      20211015 2021-10-18 (2246) 58MB -
latest/edge:      20211028 2021-11-05 (2253) 58MB

It seems the version has been switched to using date, so im closing this issue as resolved
