### ISSUE TITLE
Ubuntu 18.10

### ISSUE THREAD

**Issue by kravietz** [snapcore/core18#86]
On Ubuntu 18.10 this now throws an error, so I guess a new core is needed:

```
The linker version '2.27' used by the base 'core18' is incompatible with files in this snap:
    /home/kravietz/wps2/dist/webcookies/prime/usr/bin/python3.6 (2.28)
    /home/kravietz/wps2/dist/webcookies/prime/usr/bin/python3.6m (2.28)
    /home/kravietz/wps2/dist/webcookies/prime/usr/lib/python3.6/lib-dynload/ossaudiodev.cpython-36m-x86_64-linux-gnu.so (2.28)
    /home/kravietz/wps2/dist/webcookies/prime/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (2.28)
    /home/kravietz/wps2/dist/webcookies/prime/usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4 (2.28)
```
Can you advise how to build and use one?

**Comment by zyga** [comment]
I believe you have to build your snap on Ubuntu 18.04 (either directly or using cleanbuild). You cannot use the 18.10 archive to create snaps.

**Comment by abitrolly** [comment]
I wish `snapcraft` could warn about it before building.

**Comment by Meulengracht** [comment]
Not enough information to pursue this, and have now gone 3 years since being reported. If you still feel this is an issue, feel free to reopen this.
