### ISSUE TITLE
bash completion not installed if "core" snap is not installed

### ISSUE THREAD

**Issue by albertodonato** [snapcore/core18#89]
in a fresh Bionic container with

```
snap    2.34.2+18.04
snapd   2.34.2+18.04
series  16
ubuntu  18.04
kernel  4.15.0-36-generic
```
installing a `core18` based snap:

```
root@b:~# snap install --edge --classic sshoot
sshoot (edge) 1.4.1 from 'ack' installed
root@b:~# snap list
Name    Version  Rev  Tracking  Publisher  Notes
core18  18       442  stable    canonical  base
sshoot  1.4.1    78   edge      ack        classic
root@b:~# readlink /usr/share/bash-completion/completions/sshoot
```

the bash-completion file is not installed. Installing the `core` snap first makes it appear:

```
root@b:~# snap remove sshoot
sshoot removed
root@b:~# snap install core
2018-11-09T01:48:01Z INFO Waiting for restart...
core 16-2.35.5 from 'canonical' installed
root@b:~# snap install --edge --classic sshoot
sshoot (edge) 1.4.1 from Alberto Donato (ack) installed
root@b:~# readlink /usr/share/bash-completion/completions/sshoot
/snap/core/current/usr/lib/snapd/complete.sh
```

**Comment by albertodonato** [comment]
Not sure if related, but even after installing the `core` snap, command completion doesn't work

**Comment by chipaca** [comment]
* core18 needs to pull in the `bash-completion` package
* it should also add a symlink to the completion for snap itself, ie a `snap` symlink in `/usr/share/bash-completion/completions/` to `/snap/snapd/current/usr/share/bash-completion/completions/snap`.
I'm not sure if that'll be enough or if there need to be changes on the snapd side (there is code to handle this, but it's obviously not been tested...)

**Comment by chipaca** [comment]
This is also [lp:1825254](https://bugs.launchpad.net/snappy/+bug/1825254) fwiw

**Comment by Meulengracht** [comment]
Bash-completions has been fixed from core22+, and we wont be backporting the fix for it to core18, as its not a critical bug, it's more of a nice-to-have feature. Closing this issue as a wont-fix
