### ISSUE TITLE
i386 support missing on core18-amd64

### ISSUE THREAD

**Issue by mmtrt** [snapcore/core18#93]
as per discussion on [forum.snapcraft.io](https://forum.snapcraft.io/t/snap-with-core18-as-base-not-a-dynamic-executable-issue-on-i386-pkgs-in-amd64-snap/8775)

I was recently testing my wine snaps with core18 as base and during testing I begin to notice the issue that `i386` was completely broken on `amd64` snap.

Are there any plans for `i386` support be included on `core18 amd64`?

**Comment by zyga** [comment]
I think so, we will discuss this next week.

**Comment by sil2100** [comment]
This should be now done.
